/**
 * Common pantry/grocery ingredient names for autocomplete suggestions.
 * Sorted alphabetically within each category group.
 */
export const INGREDIENT_SUGGESTIONS: string[] = [
  // Produce
  'Beetroot',
  'Bell Pepper',
  'Broccoli',
  'Cabbage',
  'Capsicum',
  'Carrot',
  'Cauliflower',
  'Celery',
  'Coriander Leaves',
  'Corn',
  'Cucumber',
  'Eggplant',
  'Garlic',
  'Ginger',
  'Green Chili',
  'Green Onions',
  'Kale',
  'Lemon',
  'Lettuce',
  'Lime',
  'Mint',
  'Mushrooms',
  'Onion',
  'Peas',
  'Potato',
  'Pumpkin',
  'Radish',
  'Spinach',
  'Spring Onions',
  'Sweet Potato',
  'Tomato',
  'Zucchini',

  // Protein — Meat & Fish
  'Beef Steak',
  'Chicken Breast',
  'Chicken Drumsticks',
  'Chicken Thighs',
  'Chicken Wings',
  'Ground Beef',
  'Ground Chicken',
  'Ground Pork',
  'Lamb Chops',
  'Pork Belly',
  'Salmon Fillet',
  'Shrimp',
  'Tuna',

  // Protein — Eggs & Plant
  'Chickpeas',
  'Eggs',
  'Paneer',
  'Tofu',

  // Dairy
  'Butter',
  'Cheddar Cheese',
  'Condensed Milk',
  'Cream',
  'Cream Cheese',
  'Ghee',
  'Heavy Cream',
  'Milk',
  'Mozzarella',
  'Parmesan',
  'Sour Cream',
  'Yogurt',

  // Grains & Bread
  'All-Purpose Flour',
  'Basmati Rice',
  'Bread',
  'Brown Rice',
  'Cornmeal',
  'Couscous',
  'Noodles',
  'Oats',
  'Pasta',
  'Poha',
  'Quinoa',
  'Semolina',
  'Sooji',
  'White Rice',
  'Whole Wheat Flour',

  // Legumes & Lentils
  'Black Beans',
  'Black Lentils',
  'Chana Dal',
  'Green Moong',
  'Kidney Beans',
  'Red Lentils',
  'Split Peas',
  'Toor Dal',
  'Urad Dal',
  'Yellow Lentils',

  // Spices & Herbs
  'Basil',
  'Bay Leaves',
  'Black Pepper',
  'Cardamom',
  'Cayenne Pepper',
  'Chili Powder',
  'Cinnamon',
  'Cloves',
  'Coriander Powder',
  'Cumin',
  'Fennel Seeds',
  'Fenugreek',
  'Garam Masala',
  'Mustard Seeds',
  'Oregano',
  'Paprika',
  'Rosemary',
  'Star Anise',
  'Thyme',
  'Turmeric',

  // Oils
  'Coconut Oil',
  'Olive Oil',
  'Sesame Oil',
  'Vegetable Oil',

  // Pantry / Condiments
  'Baking Powder',
  'Baking Soda',
  'Brown Sugar',
  'Canned Tomatoes',
  'Coconut Milk',
  'Cornstarch',
  'Fish Sauce',
  'Hoisin Sauce',
  'Honey',
  'Hot Sauce',
  'Jaggery',
  'Ketchup',
  'Maple Syrup',
  'Mayonnaise',
  'Oyster Sauce',
  'Salt',
  'Soy Sauce',
  'Stock Cubes',
  'Sugar',
  'Tomato Paste',
  'Vinegar',
  'Worcestershire Sauce',
];
